version: "3.7"
services:
  app:
    build:
      args:
        user: xdonie11
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pos
    container_name: pos-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pos

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: pos-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
       - "3356:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - anisra

  nginx:
    image: nginx:alpine
    container_name: anisra-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - anisra

networks:
  anisra:
    driver: bridge

